# Generated by Django 4.2.7 on 2023-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicarlibro',
            old_name='cuerpo',
            new_name='enlace',
        ),
        migrations.AlterField(
            model_name='publicarlibro',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicarlibro',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='publicarlibro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
