# Generated by Django 4.2.7 on 2023-12-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_alter_comentarios_posteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='posteo',
            new_name='publicacion',
        ),
    ]
